version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db_net

    deploy:
      placement:
        constraints:
          - "node.role==manager"  
      restart_policy:
        condition: on-failure

  haproxy:
    image: haproxy:latest
    volumes:
      - ./data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro 
      - ./data/pki/issued/:/usr/local/certificates
    ports:
      - "80:80"
      - "443:443"
    networks: 
      - out_net
      - wb_net
    depends_on:
      - web
    deploy:
      placement:
        constraints:
          - "node.role==manager"
      restart_policy:
        condition: on-failure

    
  web:
    image: sh0rtcyb3r/ccdc23_af_django:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db_net
      - out_net 
    depends_on:
      - db


    deploy:
      replicas: 3
      update_config:
        parallelism: 2
      restart_policy:
        condition: on-failure

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer:/data
    ports:
      - 9000:9000

volumes: 
  db: 
  portainer:

# If this is not a swarm part the networks need to be bridged. 
networks: 
  # We want to create a network for the Web browsers to communicate with the database
  db_net: 
    driver: overlay 
    attachable: true
    # Added to make the network have no gateway configured (No internet access)
    internal: true
  # We want to create a network for the proxy to communicate with the web servers, but not the database 
  wb_net:
    driver: overlay 
    attachable: true
    # Added to make the network have no gateway configured (No internet access)
    internal: true
  # Since the proxy is using the host for portmapping does it need network access?
  out_net:
    driver: overlay  
    attachable: true
