version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db_net

  web:
    # build: ./Django_Site
    image: sh0rtcyb3r/ccdc23_af_django:latest
    #ports: # This is not needed as it does not need to be exposed, we currently have it as part of the internal network. 
      #- "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - db_net
      - wb_net

  haproxy:
    image: haproxy:latest
    volumes:
      - ./data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro 
    ports:
      - "80:80"
    depends_on:
      - web
    networks: 
      - db_net
      - wb_net
      - out_net
    restart: on-failure
    # network_mode: host

volumes: 
  db: 

# If this is not a swarm part the networks need to be bridged. 
networks: 
  # We want to create a network for the Web browsers to communicate with the database
  db_net: 
    driver: bridge 
    attachable: true
    # Added to make the network have no gateway configured (No internet access)
    internal: true
  # We want to create a network for the proxy to communicate with the web servers, but not the database 
  wb_net:
    driver: bridge 
    attachable: true
    # Added to make the network have no gateway configured (No internet access)
    internal: true
  # Since the proxy is using the host for portmapping does it need network access?
  out_net:
    driver: bridge  
    attachable: true


    
