version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - db_net

  web:
    # build: ./Django_Site
    image: sh0rtcyb3r/ccdc23_af_django:latest
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    networks:
      - db_net

  haproxy:
    image: haproxy:latest
    volumes:
      - ./data/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro 
    ports:
      - "80:80"
    depends_on:
      - web
    networks: 
      - db_net
    restart: on-failure
    # network_mode: host


volumes: 
  db: 

networks: 
  db_net: 
    driver: overlay 
    attachable: true